# Generated by Django 6.1 on 2026-08-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('operations', '0002_alter_project_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='operations.client'),
        ),
    ]
