# Generated by Django 6.1 on 2026-08-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='scrope_description',
            new_name='scope_description',
        ),
    ]
