# Generated by Django 6.1 on 2026-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_client_notes_project_description_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
